mysql:
  host:127.0.0.1
  port:3306
  db:gvb_db
  user:root
  password:root
  log_level:dev
logger:
  level:info
  prefix:'[gvb]'
  director:log
  show-line:true
  log-in-console:true
system:
  host:""
  port:""
  env:dev